/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.30
 * Generated at: 2015-12-19 11:35:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import org.codehaus.jettison.json.JSONObject;
import com.dao.BloodBankDAOImpl;
import org.codehaus.jettison.json.JSONArray;
import com.bean.Request;
import com.bean.Hospital;
import com.dao.HospitalDAOImpl;
import com.bean.BloodBank;
import java.util.List;

public final class bloodBankHome_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!--Author: W3layouts\r\n");
      out.write("Author URL: http://w3layouts.com\r\n");
      out.write("License: Creative Commons Attribution 3.0 Unported\r\n");
      out.write("License URL: http://creativecommons.org/licenses/by/3.0/\r\n");
      out.write("-->\r\n");
      out.write("<!DOCTYPE HTML>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>IBMS</title>\r\n");
      out.write("<link href=\"css/bootstrap.css\" rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\tmedia=\"all\">\r\n");
      out.write("<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->\r\n");
      out.write("<script src=\"js/jquery-1.11.0.min.js\"></script>\r\n");
      out.write("<!-- Custom Theme files -->\r\n");
      out.write("<link href=\"css/style.css\" rel=\"stylesheet\" type=\"text/css\" media=\"all\" />\r\n");
      out.write("<!-- Custom Theme files -->\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<meta name=\"keywords\" content=\"\" />\r\n");
      out.write("<script type=\"application/x-javascript\">\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t addEventListener(\"load\", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<!--Google Fonts-->\r\n");
      out.write("<link href='//fonts.googleapis.com/css?family=Squada+One'\r\n");
      out.write("\trel='stylesheet' type='text/css'>\r\n");
      out.write("<link\r\n");
      out.write("\thref='//fonts.googleapis.com/css?family=Source+Sans+Pro:400,200,300,600,700,900'\r\n");
      out.write("\trel='stylesheet' type='text/css'>\r\n");
      out.write("<!-- start-smoth-scrolling -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/move-top.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/easing.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tjQuery(document).ready(function($) {\r\n");
      out.write("\t\t$(\".scroll\").click(function(event) {\r\n");
      out.write("\t\t\tevent.preventDefault();\r\n");
      out.write("\t\t\t$('html,body').animate({\r\n");
      out.write("\t\t\t\tscrollTop : $(this.hash).offset().top\r\n");
      out.write("\t\t\t}, 1000);\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery-1.11.0.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery.validate.min.js\"></script>\r\n");
      out.write("<script src=\"//code.jquery.com/jquery-1.9.1.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"http://jqueryvalidation.org/files/dist/jquery.validate.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"http://jqueryvalidation.org/files/dist/additional-methods.min.js\"></script>\r\n");
      out.write("<script src=\"js/editDetailsValidatebb.js\">\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<!-- //end-smoth-scrolling -->\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("#center {\r\n");
      out.write("\tmargin-left: 50px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".my-error-class {\r\n");
      out.write("\tcolor: #FF0000; /* red */\r\n");
      out.write("\tdisplay: inline;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* .my-valid-class { */\r\n");
      out.write("/* \tcolor: #00CC00; /* green */\r\n");
      out.write("* /\r\n");
      out.write("\t/* } */  \r\n");
      out.write("\r\n");
      out.write(".error-password {\r\n");
      out.write("\tcolor: #FF0000;\r\n");
      out.write("\tdisplay: none;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<!-- //end-smoth-scrolling -->\r\n");
      out.write("<script src=\"js/BloodBankHome.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<!--banner start here-->\r\n");
      out.write("\t<div class=\"banner-two\">\r\n");
      out.write("\t\t<div class=\"header\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<div class=\"header-main\">\r\n");
      out.write("\t\t\t\t\t<div class=\"logo\">\r\n");
      out.write("\t\t\t\t\t\t<h1>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"index.html\">IBMS Connect</a>\r\n");
      out.write("\t\t\t\t\t\t</h1>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"top-nav\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"menu\"> <img src=\"images/icon.png\" alt=\"\" /></span>\r\n");
      out.write("\t\t\t\t\t\t<nav class=\"cl-effect-1\">\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"res\">\r\n");
      out.write("<!-- \t\t\t\t\t\t\t\t<li><a href=\"index.html\">Home</a></li> -->\r\n");
      out.write("<!-- \t\t\t\t\t\t\t\t<li><a class=\"active\" href=\"about.html\">About</a></li> -->\r\n");
      out.write("<!-- \t\t\t\t\t\t\t\t<li><a href=\"services.html\">Services</a></li> -->\r\n");
      out.write("<!-- \t\t\t\t\t\t\t\t<li><a href=\"gallery.html\">Gallery</a></li> -->\r\n");
      out.write("<!-- \t\t\t\t\t\t\t\t<li><a href=\"shortcords.html\">Short Codes</a></li> -->\r\n");
      out.write("<!-- \t\t\t\t\t\t\t\t<li><a href=\"contact.html\">Contact</a></li> -->\r\n");
      out.write("<!-- \t\t\t\t\t\t\t</ul> -->\r\n");
      out.write("\t\t\t\t\t\t\t<li>Welcome ");

								
								
									if (request.getSession(false) == null) {
										//redirect to login page 
										//alert please login
									response.sendRedirect("loginFirst.jsp");

									} else {
										BloodBank bloodBank = (BloodBank) session
												.getAttribute("bloodbank");
										Hospital hospital = (Hospital) session.getAttribute("hospital");

										if (bloodBank == null && hospital == null) {
											//redirect to login page 
											//alert please login
										} else {
											String name = "name";
											if (bloodBank != null) {
												name = bloodBank.getBloodBank_name();
											} else if (hospital != null) {
												name = hospital.getHospital_name();
											}
								
      out.write(' ');
      out.print(name);
      out.write(' ');

 	}

 	}
 
      out.write("</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a class=\"active\" href=\"about.html\">About</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>Emergency Contact: +91 (712) 66 92084</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<form action=\"LogoutServlet\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"submit\" class=\"btn btn-1 btn-primary\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvalue=\"Logout\" id=\"logout\" name=\"logout\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</nav>\r\n");
      out.write("\t\t\t\t\t\t<!-- script-for-menu -->\r\n");
      out.write("\t\t\t\t\t\t<script>\r\n");
      out.write("\t\t\t\t\t\t\t$(\"span.menu\").click(function() {\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\"ul.res\").slideToggle(300, function() {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t// Animation complete.\r\n");
      out.write("\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t\t\t<!-- /script-for-menu -->\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!--banner end here-->\r\n");
      out.write("\t<!--about start here-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"we-do\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"page-header\">\r\n");
      out.write("\t\t\t\t<nav id=\"menu\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<ul class=\"nav nav-tabs\" role=\"tablist\">\r\n");
      out.write("\t\t\t\t\t\t<li role=\"presentation\" class=\"active\" id=\"stockTab\"><a\r\n");
      out.write("\t\t\t\t\t\t\tonclick=\"return displayHandle('stockTab','stock');\">Stock\r\n");
      out.write("\t\t\t\t\t\t\t\tAvailable</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li role=\"presentation\" id=\"editDetailsTab\"><a\r\n");
      out.write("\t\t\t\t\t\t\tonclick=\"return displayHandle('editDetailsTab','editDetails1');\">Edit\r\n");
      out.write("\t\t\t\t\t\t\t\tDetails</a></li>\r\n");
      out.write("\t\t\t\t\t\t<!-- \t\t\t\t\t\t<li role=\"presentation\" id=\"pending\"><a -->\r\n");
      out.write("\t\t\t\t\t\t<!-- \t\t\t\t\t\t\thref=\"requestForm.jsp\">Pending Requests</a></li> -->\r\n");
      out.write("\t\t\t\t\t\t<li role=\"presentation\" id=\"listDonorsTab\"><a\r\n");
      out.write("\t\t\t\t\t\t\tonclick=\"return displayHandle('listDonorsTab','listDonors');\">List\r\n");
      out.write("\t\t\t\t\t\t\t\tOf Donors</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li role=\"presentation\" id=\"myRequests\"><a\r\n");
      out.write("\t\t\t\t\t\t\thref=\"MyRequests.jsp\">My Requests</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</nav>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div id=\"stock\">\r\n");
      out.write("\t\t\t\t\t<h2>STOCK AVAILABLE</h2>\r\n");
      out.write("\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t<div class=\"bs-example\" data-example-id=\"contextual-table\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"border: 1px solid #eee\">\r\n");
      out.write("\t\t\t\t\t\t<table class=\"table\">\r\n");
      out.write("\t\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>#</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>Blood Group</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>Blood Type</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>Units</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t\t<tbody>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t");

									//get bloodbankid
									BloodBank bloodBank = (BloodBank) session.getAttribute("bloodBank");
									JSONArray jsonArray = new BloodBankDAOImpl().seeStock(bloodBank
											.getBloodBank_id());
									for (int i = 0; jsonArray != null && i < jsonArray.length(); i++) {
										JSONObject jsonObject = (JSONObject) jsonArray.get(i);
								
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr class=\"info\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th scope=\"row\">");
      out.print(i + 1);
      out.write("</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>");
      out.print(jsonObject.get("bloodGroup"));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>");
      out.print(jsonObject.get("bloodType"));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>");
      out.print(jsonObject.get("quantity"));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t");

									}
								
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"listDonors\" style=\"display: none\">\r\n");
      out.write("\t\t\t\t\t<h2>List of Donors</h2>\r\n");
      out.write("\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t<div class=\"bs-example\" data-example-id=\"contextual-table\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"border: 1px solid #eee\">\r\n");
      out.write("\t\t\t\t\t\t<table class=\"table\">\r\n");
      out.write("\t\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>#</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>Name</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>Gender</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>BloodGroup</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>Email-Id</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>Contact Number</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>Address</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t\t<tbody>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t");

									bloodBank = (BloodBank) session.getAttribute("bloodBank");
									jsonArray = new BloodBankDAOImpl().seeDonors(bloodBank
											.getBloodBank_id());
									for (int i = 0; jsonArray != null && i < jsonArray.length(); i++) {
										JSONObject jsonObject = (JSONObject) jsonArray.get(i);
								
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr class=\"info\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th scope=\"row\">");
      out.print(i + 1);
      out.write("</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>");
      out.print(jsonObject.get("donorName"));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>");
      out.print(jsonObject.get("gender"));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>");
      out.print(jsonObject.get("bloodGroup"));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>");
      out.print(jsonObject.get("emailId"));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>");
      out.print(jsonObject.get("contactNo"));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>");
      out.print(jsonObject.get("donorAddress"));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t");

									}
								
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<form action=\"EditServlet\" method=\"post\" id=\"edit-form\">\r\n");
      out.write("\t\t\t\t\t<div id=\"editDetails1\" style=\"display: none\">\r\n");
      out.write("\t\t\t\t\t\t");

							BloodBank b = (BloodBank) session.getAttribute("bloodBank");
						
      out.write("<table>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>Bank Name:</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>");
      out.print(b.getBloodBank_name());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>Email:</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>");
      out.print(b.getBloodBank_emailId());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>Password:</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><a href=\"editPassword.jsp?type=bb\">Edit Password</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>B.T.O's Name:</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>");
      out.print(b.getBTO_name());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"button\" name=\"change1\" value=\"Change BTO\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tid=\"change_bto\" onclick=\"return changeBTO()\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div id=\"ChangeBTO\" style=\"display: none\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tEnter new BTO<input type=\"text\" name=\"newBTO\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>Contact no.:</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>");
      out.print(b.getBloodBank_mobileNo());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"button\" name=\"change2\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvalue=\"Change contact\" id=\"change_con\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonclick=\"return changeContact()\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div id=\"ChangeContact\" style=\"display: none\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tEnter new Contact<input type=\"text\" name=\"newContact\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>License No.:</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>");
      out.print(b.getFDA_lisenceNo());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>Circle:</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>");
      out.print(b.getBloodBank_circle());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>Address:</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>");
      out.print(b.getBloodBank_address());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>Pincode:</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>");
      out.print(b.getBloodBank_pin());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>Functional:</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>");
      out.print(b.isFunctional());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"submit\" name=\"Change\" value=\"Submit\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
