/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.30
 * Generated at: 2015-12-21 07:18:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.bean.Request;
import com.bean.Hospital;
import com.dao.HospitalDAOImpl;
import com.bean.BloodBank;
import java.util.List;

public final class HospitalHome_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!--Author: W3layouts\r\n");
      out.write("Author URL: http://w3layouts.com\r\n");
      out.write("License: Creative Commons Attribution 3.0 Unported\r\n");
      out.write("License URL: http://creativecommons.org/licenses/by/3.0/\r\n");
      out.write("-->\r\n");
      out.write("<!DOCTYPE HTML>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>IBMS</title>\r\n");
      out.write("<link href=\"css/bootstrap.css\" rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\tmedia=\"all\" />\r\n");
      out.write("\r\n");
      out.write("<link href=\"css/style.css\" rel=\"stylesheet\" type=\"text/css\" media=\"all\" />\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<meta name=\"keywords\" content=\"\" />\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"application/x-javascript\">\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t addEventListener(\"load\", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<!--Google Fonts-->\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/move-top.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/easing.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t\r\n");
      out.write("\tjQuery(document).ready(function($) {\r\n");
      out.write("\t\t$(\".scroll\").click(function(event) {\r\n");
      out.write("\t\t\tevent.preventDefault();\r\n");
      out.write("\t\t\t$('html,body').animate({\r\n");
      out.write("\t\t\t\tscrollTop : $(this.hash).offset().top\r\n");
      out.write("\t\t\t}, 1000);\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery-1.11.0.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery.validate.min.js\"></script>\r\n");
      out.write("<script src=\"http://jqueryvalidation.org/files/dist/additional-methods.min.js\"></script>\r\n");
      out.write("<script src=\"js/RequestForm.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script src=\"//code.jquery.com/jquery-1.9.1.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"js/editDetailsValidate.js\"></script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("#center {\r\n");
      out.write("\tmargin-left: 50px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* .my-valid-class { */\r\n");
      out.write("/* \tcolor: #00CC00; /* green */\r\n");
      out.write("\r\n");
      out.write("\t/* } */         \r\n");
      out.write("\r\n");
      out.write(".error-password {\r\n");
      out.write("\tcolor: #FF0000;\r\n");
      out.write("\tdisplay: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".my-error-class {\r\n");
      out.write("\tcolor: #FF0000; /* red */\r\n");
      out.write("\tdisplay: inline;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script src=\"js/HospitalHome.js\"></script>\r\n");
      out.write("<script src=\"http://maps.google.com/maps/api/js?sensor=false\" \r\n");
      out.write("          type=\"text/javascript\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<!--banner start here-->\r\n");
      out.write("\t<div class=\"banner-two\">\r\n");
      out.write("\t\t<div class=\"header\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<div class=\"header-main\">\r\n");
      out.write("\t\t\t\t\t<div class=\"logo\">\r\n");
      out.write("\t\t\t\t\t\t<h1>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"\"> IBMS Connect</a>\r\n");
      out.write("\t\t\t\t\t\t</h1>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"top-nav\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"menu\"> <img src=\"images/icon.png\" alt=\"\" /></span>\r\n");
      out.write("\t\t\t\t\t\t<nav class=\"cl-effect-1\">\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"res\">\r\n");
      out.write("<!-- \t\t\t\t\t\t\t\t<li><a href=\"index.html\">Home</a></li> -->\r\n");
      out.write("<!-- \t\t\t\t\t\t\t\t<li><a class=\"active\" href=\"about.jsp\">About</a></li> -->\r\n");
      out.write("<!-- \t\t\t\t\t\t\t\t<li><a href=\"services.html\">Services</a></li> -->\r\n");
      out.write("<!-- \t\t\t\t\t\t\t\t<li><a href=\"gallery.html\">Gallery</a></li> -->\r\n");
      out.write("<!-- \t\t\t\t\t\t\t\t<li><a href=\"shortcords.html\">Short Codes</a></li> -->\r\n");
      out.write("<!-- \t\t\t\t\t\t\t\t<li><a href=\"contact.html\">Contact</a></li> -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>Welcome ");

								
								
									if (request.getSession(false) == null) {
										//redirect to login page 
										//alert please login
									response.sendRedirect("loginFirst.jsp");

									} else {
										BloodBank bloodBank = (BloodBank) session
												.getAttribute("bloodbank");
										Hospital hospital = (Hospital) session.getAttribute("hospital");

										if (bloodBank == null && hospital == null) {
											//redirect to login page 
											//alert please login
										} else {
											String name = "name";
											if (bloodBank != null) {
												name = bloodBank.getBloodBank_name();
											} else if (hospital != null) {
												name = hospital.getHospital_name();
											}
								
      out.write(' ');
      out.print(name);
      out.write(' ');

 	}

 	}
 
      out.write("</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a class=\"active\" href=\"about.html\">About</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>Emergency Contact: +91 (712) 66 92084</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<form action=\"LogoutServlet\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"submit\" class=\"btn btn-1 btn-primary\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvalue=\"Logout\" id=\"logout\" name=\"logout\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li>Welcome ");

								
								
									if (request.getSession(false) == null) {
										//redirect to login page 
										//alert please login
									response.sendRedirect("loginFirst.jsp");

									} else {
										BloodBank bloodBank = (BloodBank) session
												.getAttribute("bloodbank");
										Hospital hospital = (Hospital) session.getAttribute("hospital");

										if (bloodBank == null && hospital == null) {
											//redirect to login page 
											//alert please login
										} else {
											String name = "name";
											if (bloodBank != null) {
												name = bloodBank.getBloodBank_name();
											} else if (hospital != null) {
												name = hospital.getHospital_name();
											}
								
      out.write(' ');
      out.print(name);
      out.write(' ');

 	}

 	}
 
      out.write("</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a class=\"active\" href=\"about.html\">About</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>Emergency Contact: +91 (712) 66 92084</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<form action=\"LogoutServlet\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"submit\" class=\"btn btn-1 btn-primary\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvalue=\"Logout\" id=\"logout\" name=\"logout\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</nav>\r\n");
      out.write("\t\t\t\t\t\t<!-- script-for-menu -->\r\n");
      out.write("\t\t\t\t\t\t<script>\r\n");
      out.write("\t\t\t\t\t\t\t$(\"span.menu\").click(function() {\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\"ul.res\").slideToggle(300, function() {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t// Animation complete.\r\n");
      out.write("\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t\t\t<!-- /script-for-menu -->\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!--banner end here-->\r\n");
      out.write("\t<!--about start here-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"we-do\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"page-header\">\r\n");
      out.write("\t\t\t\t<nav id=\"menu\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"nav nav-tabs\" role=\"tablist\">\r\n");
      out.write("\t\t\t\t\t\t<li role=\"presentation\" class=\"active\" id=\"listBanksTab\"><a\r\n");
      out.write("\t\t\t\t\t\t\tonclick=\"return displayHandle('listBanksTab','listAllBB');\">List\r\n");
      out.write("\t\t\t\t\t\t\t\tBloodbanks</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li role=\"presentation\" id=\"editDetailsTab\"><a\r\n");
      out.write("\t\t\t\t\t\t\tonclick=\"return displayHandle('editDetailsTab','editDetails');\">Edit\r\n");
      out.write("\t\t\t\t\t\t\t\tdetails</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li role=\"presentation\" id=\"requestBloodTab\"><a\r\n");
      out.write("\t\t\t\t\t\t\tonclick=\"return displayHandle('requestBloodTab','requestForm');\">Request\r\n");
      out.write("\t\t\t\t\t\t\t\tBlood</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li role=\"presentation\" id=\"cancelRequestTab\"><a\r\n");
      out.write("\t\t\t\t\t\t\tonclick=\"return displayHandle('cancelRequestTab','cancelRequest');\">Cancel\r\n");
      out.write("\t\t\t\t\t\t\t\tRequests</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li role=\"presentation\" id=\"viewRequestTab\"><a\r\n");
      out.write("\t\t\t\t\t\t\tonclick=\"return displayHandle('viewRequestTab','listAllRequests');\">My\r\n");
      out.write("\t\t\t\t\t\t\t\tRequests</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</nav>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div id=\"listAllBB\">\r\n");
      out.write("\t\t\t\t<!-- \t\t\t\tstyle=\"display: none\"> -->\r\n");
      out.write("\t\t\t\t<h2>BLODDBANKS</h2>\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t<div id=\"map\" style=\"width: 500px; height: 400px;\"></div>\r\n");
      out.write("\t\t\t\t<div class=\"bs-example\" data-example-id=\"contextual-table\"\r\n");
      out.write("\t\t\t\t\tstyle=\"border: 1px solid #eee\">\r\n");
      out.write("\t\t\t\t\t<table class=\"table\">\r\n");
      out.write("\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>#</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>Bloodbank Name</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>Address</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>Contact No.</th>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\t");

								List<BloodBank> bbs = (new HospitalDAOImpl()).getAllBloodbanks();
								int k = 1;
								if (bbs != null && bbs.size() != 0)
									for (BloodBank b : bbs) {
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<tr class=\"info\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<th scope=\"row\">");
      out.print(k);
      out.write("</th>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><a href=\"\">");
      out.print(b.getBloodBank_name());
      out.write(" </a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>");
      out.print(b.getBloodBank_address());
      out.write("</td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>");
      out.print(b.getBloodBank_mobileNo());
      out.write("</td>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t");

								k++;
									}
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"requestForm\" style=\"display: none\">\r\n");
      out.write("\t\t\t<p class=\"instruction\">*All Fields are mandatory</a>\r\n");
      out.write("\t\t\t\t<form id=\"request-form\" name=\"request\" action=\"RequestSubmission\"\r\n");
      out.write("\t\t\t\t\tmethod=\"post\">\r\n");
      out.write("\t\t\t\t\t<table align=center>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>Patient's Name:</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input id=\"patientName\" name=\"patientname\" type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"form-control\" placeholder=\"Patient Name\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"width: 300px;\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>Doctor's Name:</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input id=\"doctorName\" name=\"doctorname\" type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"form-control\" placeholder=\"Doctor Name\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"width: 300px;\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>Required Blood Group:</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><select name=\"rbg\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"default\">-Choose-</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"O_POSITIVE\">O+</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"O_NEGATIVE\">O-</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"A_POSITIVE\">A+</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"A_NEGATIVE\">A-</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"B_POSITIVE\">B+</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"B_NEGATIVE\">B-</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"AB_POSITIVE\">AB+</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"AB_NEGATIVE\">AB-</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t</select></td>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>Time of requirement:</td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input name=\"requiredTime\" type=\"date\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"form-control\" placeholder=\"Time of requirement\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>Units:</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input id=\"units\" type=\"number\" name=\"units\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"form-control\" placeholder=\"0\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>Type of blood:</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><select name=\"bloodtype\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"default\">-Choose-</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"PRC\">PRC</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"PC\">PC</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"FFP\">FFP</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"WB\">Whole Blood</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t</select></td>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"submit\" class=\"btn btn-default\">Submit</button>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<!-- \t\t\t\t<form id=\"request-form\" name=\"request\" action=\"RequestSubmission\" -->\r\n");
      out.write("\t\t\t\t<!-- \t\t\t\t\tmethod=\"post\"> -->\r\n");
      out.write("\t\t\t\t<!-- \t\t\t\t\t<div> -->\r\n");
      out.write("\t\t\t\t<!-- \t\t\t\t\t\tPatient's Name: <input id=\"patientName\" name=\"patientname\" -->\r\n");
      out.write("\t\t\t\t<!-- \t\t\t\t\t\t\ttype=\"text\"> -->\r\n");
      out.write("\t\t\t\t<!-- \t\t\t\t\t</div> -->\r\n");
      out.write("\t\t\t\t<!-- \t\t\t\t\t<div> -->\r\n");
      out.write("\t\t\t\t<!-- \t\t\t\t\t\tDoctor's Name: <input id=\"doctorName\" name=\"doctorname\" -->\r\n");
      out.write("\t\t\t\t<!-- \t\t\t\t\t\t\ttype=\"text\"> -->\r\n");
      out.write("\t\t\t\t<!-- \t\t\t\t\t</div> -->\r\n");
      out.write("\t\t\t\t<!-- \t\t\t\t\t<div> -->\r\n");
      out.write("\t\t\t\t<!-- \t\t\t\t\t\tRequired Blood Group: <select name=\"rbg\"> -->\r\n");
      out.write("\t\t\t\t<!-- \t\t\t\t\t\t\t<option value=\"default\">-Choose-</option> -->\r\n");
      out.write("\t\t\t\t<!-- \t\t\t\t\t\t\t<option value=\"O_POSITIVE\">O+</option> -->\r\n");
      out.write("\t\t\t\t<!-- \t\t\t\t\t\t\t<option value=\"O_NEGATIVE\">O-</option> -->\r\n");
      out.write("\t\t\t\t<!-- \t\t\t\t\t\t\t<option value=\"A_POSITIVE\">A+</option> -->\r\n");
      out.write("\t\t\t\t<!-- \t\t\t\t\t\t\t<option value=\"A_NEGATIVE\">A-</option> -->\r\n");
      out.write("\t\t\t\t<!-- \t\t\t\t\t\t\t<option value=\"B_POSITIVE\">B+</option> -->\r\n");
      out.write("\t\t\t\t<!-- \t\t\t\t\t\t\t<option value=\"B_NEGATIVE\">B-</option> -->\r\n");
      out.write("\t\t\t\t<!-- \t\t\t\t\t\t\t<option value=\"AB_POSITIVE\">AB+</option> -->\r\n");
      out.write("\t\t\t\t<!-- \t\t\t\t\t\t\t<option value=\"AB_NEGATIVE\">AB-</option> -->\r\n");
      out.write("\t\t\t\t<!-- \t\t\t\t\t\t</select> -->\r\n");
      out.write("\t\t\t\t<!-- \t\t\t\t\t</div> -->\r\n");
      out.write("\t\t\t\t<!-- \t\t\t\t\t<div> -->\r\n");
      out.write("\t\t\t\t<!-- \t\t\t\t\t\tTime of requirement:<input name=\"requiredtime\" type=\"date\"> -->\r\n");
      out.write("\t\t\t\t<!-- \t\t\t\t\t</div> -->\r\n");
      out.write("\t\t\t\t<!-- \t\t\t\t\t<div> -->\r\n");
      out.write("\t\t\t\t<!-- \t\t\t\t\t\tUnits:<input id=\"units\" type=\"number\" name=\"units\"> -->\r\n");
      out.write("\t\t\t\t<!-- \t\t\t\t\t</div> -->\r\n");
      out.write("\t\t\t\t<!-- \t\t\t\t\t<div> -->\r\n");
      out.write("\t\t\t\t<!-- \t\t\t\t\t\tType of blood: <select name=\"bloodtype\"> -->\r\n");
      out.write("\t\t\t\t<!-- \t\t\t\t\t\t\t<option value=\"default\">-Choose-</option> -->\r\n");
      out.write("\t\t\t\t<!-- \t\t\t\t\t\t\t<option value=\"PRC\">PRC</option> -->\r\n");
      out.write("\t\t\t\t<!-- \t\t\t\t\t\t\t<option value=\"PC\">PC</option> -->\r\n");
      out.write("\t\t\t\t<!-- \t\t\t\t\t\t\t<option value=\"FFP\">FFP</option> -->\r\n");
      out.write("\t\t\t\t<!-- \t\t\t\t\t\t\t<option value=\"WB\">Whole Blood</option> -->\r\n");
      out.write("\t\t\t\t<!-- \t\t\t\t\t\t</select> -->\r\n");
      out.write("\t\t\t\t<!-- \t\t\t\t\t</div> -->\r\n");
      out.write("\t\t\t\t<!-- \t\t\t\t\t<input type=\"submit\" value=\"Submit\"> -->\r\n");
      out.write("\t\t\t\t<!-- \t\t\t\t</form> -->\r\n");
      out.write("\t\t\t\t");

					List<String> errorMessages = (List<String>) session
							.getAttribute("errorMessages");
					if (errorMessages != null) {
						for (String s : errorMessages) {
							out.println("<BR>");
							out.println(s);
						}
					}
				
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"listAllRequests\" style=\"display: none\">\r\n");
      out.write("\t\t\t\t<section id=\"container\">\r\n");
      out.write("\t\t\t\t\t<!-- \t\t\t\t\t<div class=\"we-do\"> -->\r\n");
      out.write("\t\t\t\t\t<!-- \t\t\t\t\t\t<div class=\"container\"> -->\r\n");
      out.write("\t\t\t\t\t<!-- \t\t\t\t\t\t\t<div class=\"page-header\"> -->\r\n");
      out.write("\t\t\t\t\t<nav id=\"menu\">\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"nav nav-tabs\" role=\"tablist\">\r\n");
      out.write("\t\t\t\t\t\t\t<li role=\"presentation\" class=\"active\" id=\"allTab\"><a\r\n");
      out.write("\t\t\t\t\t\t\t\tonclick=\"return displayHandle('allTab','allRequests');\">All</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li role=\"presentation\" id=\"fulfilledTab\"><a\r\n");
      out.write("\t\t\t\t\t\t\t\tonclick=\"return displayHandle('fulfilledTab','fulfilledRequests');\">Fulfilled</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<li role=\"presentation\" id=\"dispatchedTab\"><a\r\n");
      out.write("\t\t\t\t\t\t\t\tonclick=\"return displayHandle('dispatchedTab','dispatchedRequests');\">Dispatched</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<li role=\"presentation\" id=\"inprogressTab\"><a\r\n");
      out.write("\t\t\t\t\t\t\t\tonclick=\"return displayHandle('inprogressTab','progressRequests');\">In\r\n");
      out.write("\t\t\t\t\t\t\t\t\tprogress</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li role=\"presentation\" id=\"cancelledTab\"><a\r\n");
      out.write("\t\t\t\t\t\t\t\tonclick=\"return displayHandle('cancelledTab','cancelledRequests');\">Cancelled</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</nav>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- \t\t\t\t\t\t\t\t<section id=\"content\"></section> -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- \t\t\t\t\t\t\t</div> -->\r\n");
      out.write("\t\t\t\t\t<!-- \t\t\t\t\t\t</div> -->\r\n");
      out.write("\t\t\t\t\t<!-- \t\t\t\t\t</div> -->\r\n");
      out.write("\t\t\t\t</section>\r\n");
      out.write("\t\t\t\t<div id=\"allRequests\" style=\"display: none\">\r\n");
      out.write("\t\t\t\t\t<div class=\"bs-example\" data-example-id=\"contextual-table\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"border: 1px solid #eee\">\r\n");
      out.write("\t\t\t\t\t\t<table class=\"table\">\r\n");
      out.write("\t\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>#</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>Request ID</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>Patient's Name</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>Blood Bank</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>Quantity</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>Delivery Date And Time</th>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t\t<tbody>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t");

									Hospital hospital = (Hospital) session.getAttribute("hospital");

									List<Request> requests = (new HospitalDAOImpl())
											.seeAllRequests(hospital);
									k = 1;
									if (requests != null && requests.size() != 0)
										for (Request req : requests) {
								
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr class=\"info\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th scope=\"row\">");
      out.print(k);
      out.write("</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><Details>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<summary>");
      out.print(req.getRequestId());
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</summary>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tDoctor's Name :\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t");
      out.print(req.getDoctor_name());
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<br> Blood Type :\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t");
      out.print(req.getBloodType());
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<br> Status :\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t");
      out.print(req.getStatus());
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</Details></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>");
      out.print(req.getPatient_name());
      out.write("</td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

										BloodBank bank = req.getBloodBank();
												if (bank != null) {
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>");
      out.print(bank.getBloodBank_name());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

										} else {
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>-</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

										}
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>");
      out.print(req.getQuantity_required());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>");
      out.print(req.getDelivery_date_time());
      out.write("</td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t");

									k++;
										}
								
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("<div id=\"fulfilledRequests\" style=\"display: none\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"bs-example\" data-example-id=\"contextual-table\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"border: 1px solid #eee\">\r\n");
      out.write("\t\t\t\t\t\t<table class=\"table\">\r\n");
      out.write("\t\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>#</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>Request ID</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>Patient's Name</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>Blood Bank</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>Quantity</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>Delivery Date And Time</th>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t\t<tbody>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t");

									hospital = (Hospital) session.getAttribute("hospital");
									requests = (new HospitalDAOImpl()).seeFulfilledRequests(hospital);
									k = 1;
									if (requests != null && requests.size() != 0)
										for (Request req : requests) {
								
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr class=\"info\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th scope=\"row\">");
      out.print(k);
      out.write("</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><Details>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<summary>");
      out.print(req.getRequestId());
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</summary>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tDoctor's Name :\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t");
      out.print(req.getDoctor_name());
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<br> Blood Type :\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t");
      out.print(req.getBloodType());
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<br> Status :\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t");
      out.print(req.getStatus());
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</Details></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>");
      out.print(req.getPatient_name());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

										BloodBank bank = req.getBloodBank();
												if (bank != null) {
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>");
      out.print(bank.getBloodBank_name());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

										} else {
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>-</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

										}
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>");
      out.print(req.getQuantity_required());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>");
      out.print(req.getDelivery_date_time());
      out.write("</td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t");

									k++;
										}
								
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div id=\"dispatchedRequests\" style=\"display: none\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"bs-example\" data-example-id=\"contextual-table\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"border: 1px solid #eee\">\r\n");
      out.write("\t\t\t\t\t\t<table class=\"table\">\r\n");
      out.write("\t\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>#</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>Request ID</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>Patient's Name</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>Blood Bank</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>Quantity Required</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>Quantity Dispatched</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>Delivery Date And Time</th>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t\t<tbody>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t");

									hospital = (Hospital) session.getAttribute("hospital");
									requests = (new HospitalDAOImpl()).seeDispatchedRequests(hospital);
									k = 1;
									if (requests != null && requests.size() != 0)
										for (Request req : requests) {
								
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr class=\"info\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th scope=\"row\">");
      out.print(k);
      out.write("</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><Details>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<summary>");
      out.print(req.getRequestId());
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</summary>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tDoctor's Name :\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t");
      out.print(req.getDoctor_name());
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<br> Blood Type :\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t");
      out.print(req.getBloodType());
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<br> Status :\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t");
      out.print(req.getStatus());
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</Details></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>");
      out.print(req.getPatient_name());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

										BloodBank bank = req.getBloodBank();
												if (bank != null) {
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>");
      out.print(bank.getBloodBank_name());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

										} else {
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>-</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

										}
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>");
      out.print(req.getQuantity_required());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>");
      out.print(req.getQuantity_received() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>");
      out.print(req.getDelivery_date_time());
      out.write("</td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t");

									k++;
										}
								
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"progressRequests\" style=\"display: none\">\r\n");
      out.write("\t\t\t\t\t<div class=\"bs-example\" data-example-id=\"contextual-table\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"border: 1px solid #eee\">\r\n");
      out.write("\t\t\t\t\t\t<table class=\"table\">\r\n");
      out.write("\t\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>#</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>Request ID</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>Patient's Name</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>Blood Bank</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>Quantity</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>Delivery Date And Time</th>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t");

									hospital = (Hospital) session.getAttribute("hospital");
									requests = (new HospitalDAOImpl()).seeInProgressRequests(hospital);
									k = 1;
									if (requests != null && requests.size() != 0)
										for (Request req : requests) {
								
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr class=\"info\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th scope=\"row\">");
      out.print(k);
      out.write("</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><Details>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<summary>");
      out.print(req.getRequestId());
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</summary>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tDoctor's Name :\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t");
      out.print(req.getDoctor_name());
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<br> Blood Type :\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t");
      out.print(req.getBloodType());
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<br> Status :\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t");
      out.print(req.getStatus());
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</Details></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>");
      out.print(req.getPatient_name());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

										BloodBank bank = req.getBloodBank();
												if (bank != null) {
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>");
      out.print(bank.getBloodBank_name());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

										} else {
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>-</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

										}
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>");
      out.print(req.getQuantity_required());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>");
      out.print(req.getDelivery_date_time());
      out.write("</td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t");

									k++;
										}
								
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"cancelledRequests\" style=\"display: none\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"bs-example\" data-example-id=\"contextual-table\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"border: 1px solid #eee\">\r\n");
      out.write("\t\t\t\t\t\t<table class=\"table\">\r\n");
      out.write("\t\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>#</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>Request ID</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>Patient's Name</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>Blood Bank</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>Quantity</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>Delivery Date And Time</th>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t\t<tbody>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t");

									hospital = (Hospital) session.getAttribute("hospital");
									requests = (new HospitalDAOImpl()).seeCancelledRequests(hospital);
									k = 1;
									if (requests != null && requests.size() != 0)
										for (Request req : requests) {
								
      out.write("<tr class=\"info\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th scope=\"row\">");
      out.print(k);
      out.write("</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><Details>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<summary>");
      out.print(req.getRequestId());
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</summary>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tDoctor's Name :\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t");
      out.print(req.getDoctor_name());
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<br> Blood Type :\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t");
      out.print(req.getBloodType());
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<br> Status :\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t");
      out.print(req.getStatus());
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</Details></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>");
      out.print(req.getPatient_name());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

										BloodBank bank = req.getBloodBank();
												if (bank != null) {
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>");
      out.print(bank.getBloodBank_name());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

										} else {
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>-</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

										}
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>");
      out.print(req.getQuantity_required());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>");
      out.print(req.getDelivery_date_time());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t");

									k++;
										}
								
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div id=\"editDetails\" style=\"display: none\">\r\n");
      out.write("\t\t\t\t<form action=\"EditDetailsHospitalServlet\" method=\"post\"\r\n");
      out.write("\t\t\t\t\tid=\"edit-form\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t");

						Hospital h = (Hospital) session.getAttribute("hospital");
					
      out.write("<table>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>Hospital Name:</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>");
      out.print(h.getHospital_name());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>Email:</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>");
      out.print(h.getHospital_email());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>Password:</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td> \r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"editPassword.jsp?type=h\">Edit Password</a>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>Officer's Name:</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>");
      out.print(h.getOfficer_name());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input type=\"button\" name=\"change1\"\r\n");
      out.write("\t\t\t\t\t\t\t\tvalue=\"Change offficer\" id=\"change_off\"\r\n");
      out.write("\t\t\t\t\t\t\t\tonclick=\"return changeOfficer()\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<div id=\"ChangeOfficer\" style=\"display: none\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\tEnter new Officer<input type=\"text\" name=\"newOfficer\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>Contact No.:</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>");
      out.print(h.getHospital_contactNo());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input type=\"button\" name=\"change2\"\r\n");
      out.write("\t\t\t\t\t\t\t\tvalue=\"Change Contact\" id=\"change_con\"\r\n");
      out.write("\t\t\t\t\t\t\t\tonclick=\"return changeContact()\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<div id=\"ChangeContact\" style=\"display: none\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\tEnter new Contact<input type=\"number\" name=\"newNumber\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- \t\t\t\t\t\t\t\t\t<input type=\"submit\" name=\"Change\"> -->\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>License No.:</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>");
      out.print(h.getHospital_lisenceNo());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>Certification:</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>");
      out.print(h.getHospital_certification());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>Address:</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>");
      out.print(h.getHospital_address());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>Pincode:</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>");
      out.print(h.getHospital_pin());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t<input type=\"submit\" name=\"Change\"\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"cancelRequest\" style=\"display: none\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"bs-example\" data-example-id=\"contextual-table\"\r\n");
      out.write("\t\t\t\t\tstyle=\"border: 1px solid #eee\">\r\n");
      out.write("\t\t\t\t\t<table class=\"table\">\r\n");
      out.write("\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>#</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>Request ID</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>Patient's Name</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>Blood Bank</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>Quantity</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>Delivery Date And Time</th>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t<tbody>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t");

								hospital = (Hospital) session.getAttribute("hospital");
								requests = (new HospitalDAOImpl()).seeInProgressRequests(hospital);
								k = 1;
								if (requests != null && requests.size() != 0)
									for (Request req : requests) {
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<tr class=\"info\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<th scope=\"row\">");
      out.print(k);
      out.write("</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><Details>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<summary>");
      out.print(req.getRequestId());
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</summary>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tDoctor's Name :\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");
      out.print(req.getDoctor_name());
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<br> Blood Type :\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");
      out.print(req.getBloodType());
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<br> Status :\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");
      out.print(req.getStatus());
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</Details></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>");
      out.print(req.getPatient_name());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t");

										BloodBank bank = req.getBloodBank();
												if (bank != null) {
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>");
      out.print(bank.getBloodBank_name());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

										} else {
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>-</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

										}
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>");
      out.print(req.getQuantity_required());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>");
      out.print(req.getDelivery_date_time());
      out.write("</td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><form action=\"CancelRequestServlet\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"rId\" value=");
      out.print(req.getRequestId());
      out.write(">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"submit\" name=\"Cancel_Request\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvalue=\"CancelRequest\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</form></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t");

								k++;
									}
							
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("\tfunction getParameterByName(name) {\r\n");
      out.write("\t\tname = name.replace(/[\\[]/, \"\\\\[\").replace(/[\\]]/, \"\\\\]\");\r\n");
      out.write("\t\tvar regex = new RegExp(\"[\\\\?&]\" + name + \"=([^&#]*)\"), results = regex\r\n");
      out.write("\t\t\t\t.exec(location.search);\r\n");
      out.write("\t\treturn results === null ? \"\" : decodeURIComponent(results[1].replace(\r\n");
      out.write("\t\t\t\t/\\+/g, \" \"));\r\n");
      out.write("\t}\r\n");
      out.write("\tvar prodId = getParameterByName('submit');\r\n");
      out.write("\tif (prodId == null) {\r\n");
      out.write("\r\n");
      out.write("\t} else {\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("\tif (prodId != null && prodId==\"1\") {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\talert('Request Submitted');\r\n");
      out.write("\t\tdisplayHandle('requestBloodTab', 'requestForm');\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\tif (prodId != null && prodId.localeCompare(\"2\") == 0) {\r\n");
      out.write("\t\tdisplayHandle('requestBloodTab', 'requestForm');\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("\tif (prodId != null && prodId.localeCompare(\"3\") == 0) {\r\n");
      out.write("\r\n");
      out.write("\tdisplayHandle('editDetailsTab','editDetails')\r\n");
      out.write("\t}\t\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("    var locations = [\r\n");
      out.write("      ['Bloodbank1', -33.890542, 151.274856, 4],\r\n");
      out.write("      ['Bloodbank2', -33.923036, 151.259052, 5],\r\n");
      out.write("     \r\n");
      out.write("    ];\r\n");
      out.write("\r\n");
      out.write("    var map = new google.maps.Map(document.getElementById('map'), {\r\n");
      out.write("      zoom: 10,\r\n");
      out.write("      center: new google.maps.LatLng(-33.92, 151.25),\r\n");
      out.write("      mapTypeId: google.maps.MapTypeId.ROADMAP\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    var infowindow = new google.maps.InfoWindow();\r\n");
      out.write("\r\n");
      out.write("    var marker, i;\r\n");
      out.write("\r\n");
      out.write("    for (i = 0; i < locations.length; i++) {  \r\n");
      out.write("      marker = new google.maps.Marker({\r\n");
      out.write("        position: new google.maps.LatLng(locations[i][1], locations[i][2]),\r\n");
      out.write("        map: map\r\n");
      out.write("      });\r\n");
      out.write("\r\n");
      out.write("      google.maps.event.addListener(marker, 'click', (function(marker, i) {\r\n");
      out.write("        return function() {\r\n");
      out.write("          infowindow.setContent(locations[i][0]);\r\n");
      out.write("          infowindow.open(map, marker);\r\n");
      out.write("        }\r\n");
      out.write("      })(marker, i));\r\n");
      out.write("    }\r\n");
      out.write("  </script>\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
