/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.30
 * Generated at: 2015-12-19 10:51:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.dao.BloodBankDAOImpl;
import com.bean.Request;
import com.dao.HospitalDAOImpl;
import com.bean.BloodBank;
import java.io.*;
import java.text.*;
import java.util.*;

public final class MyRequests_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/ackdeny.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"listAllrequest\">\r\n");
      out.write("\r\n");
      out.write("\t\t<h2>My Requests</h2>\r\n");
      out.write("\t\t<p class=\"instruction\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<table>\r\n");
      out.write("\t\t\t<tbody>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>Acknowledge</td>\r\n");
      out.write("\t\t\t\t<td>Press when cross-matching successful</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>Deny</td>\r\n");
      out.write("\t\t\t\t<td>Press when delivery cannot be made due to any reason</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t</tbody>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<a href=\"bloodBankHome.jsp\">Home</a>\r\n");
      out.write("\r\n");
      out.write("\t\t<p>\r\n");
      out.write("\t\t<div class=\"bs-example\" data-example-id=\"contextual-table\"\r\n");
      out.write("\t\t\tstyle=\"border: 1px solid #eee\">\r\n");
      out.write("\t\t\t<table class=\"table\">\r\n");
      out.write("\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<th colspan=\"1\">Request ID</th>\r\n");
      out.write("\t\t\t\t\t\t<th colspan=\"1\">Blood Group</th>\r\n");
      out.write("\t\t\t\t\t\t<th colspan=\"1\">Blood Type</th>\r\n");
      out.write("\t\t\t\t\t\t<th colspan=\"1\">Quantity required</th>\r\n");
      out.write("\t\t\t\t\t\t<th>Time of delivery</th>\r\n");
      out.write("\t\t\t\t\t\t<th>Units</th>\r\n");
      out.write("\t\t\t\t\t\t<th>Acknowledge</th>\r\n");
      out.write("\t\t\t\t\t\t<th>Deny</th>\r\n");
      out.write("\t\t\t\t\t\t<!-- \t\t\t\t\t\t\t\t\t<th>Dispatch</th> -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t<tr class=\"info\">\r\n");
      out.write("\t\t\t\t\t\t<th scope=\"row\">1</th>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");

							BloodBankDAOImpl bbd = new BloodBankDAOImpl();
							BloodBank bank = (BloodBank) session.getAttribute("bloodBank");
							List<Request> bbs = bbd.seeAllRequests(bank);
							if (bbs != null) {
								for (Request r : bbs) {
									int available = Integer.parseInt(bbd.getUnits(bank,
											r.getBloodgroup(), r.getBloodType()));
									int required = r.getQuantity_required();
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.print("REQ" + r.getRequestId());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.print(r.getBloodgroup());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.print(r.getBloodType());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.print(required);
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t<td>");
      out.print(r.getDelivery_date_time());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t<form action=\"BloodBankServlet\">\r\n");
      out.write("\t\t\t\t\t\t\t<td><input type=\"hidden\" value=\"");
      out.print(r.getRequestId());
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\t\t\tname=\"rId\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>");
      out.print(available);
      out.write("</td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t");

								if (r.getStatus() == 1) {
											
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<td><input type=\"submit\" name=\"process\" value=\"Acknowledge\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input type=\"submit\" name=\"process\" value=\"Deny\"></td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t");

								
										} else {
							
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<td><input type=\"submit\" name=\"process\" value=\"Acknowledge\"\r\n");
      out.write("\t\t\t\t\t\t\t\tdisabled=\"disabled\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input type=\"submit\" name=\"process\" value=\"Deny\"\r\n");
      out.write("\t\t\t\t\t\t\t\tdisabled=\"disabled\"></td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t");

						}
							}
						}
					
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t</p>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
